### ISSUE TITLE
Banning ligrev (or users with more than one resource as the same nick?) breaks the user-tracker

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#171]
Reproduce:
* Ban Ligrev (or possibly any user with two resources sharing a nick in the same room?)
* get the following prompt:

    (2015-03-25 04:48:34) Ligrev: Ligrev has been banned from Ligrev's Lounge.
    (2015-03-25 04:48:34) Ligrev: {user} has been banned from Ligrev's Lounge.
* Watch as user logins, logouts, and nick changes aren't shown, as the user sidebar doesn't update, and Ligrev posts (when she logs back in) are formatted as ordinary messages, not with Ligrev's CSS.

**Comment by cburschka** [comment]
I'll have to test this extensively.

As far as I'm aware, multi-resource tracking has always been badly broken in ejabberd - for example, only the last resource to leave triggers an unavailable presence when leaving normally. I guess /ban is an exception to this...

**Comment by cburschka** [comment]
Okay, so... the user list is buggy, so that if the nth user logs out, instead of only deleting the nth entry from the index it deletes n entries starting at n. :derp:

This only immediately affects the sort index, not the visual list, but future additions and removals use that index and will fail in weird and unpredictable ways.

The patch for #144 might fix quite a few weird bugs we've been experiencing since 1.5.

**Comment by cburschka** [comment]
I'm going to need to create a test account for this.

**Comment by cburschka** [comment]
Okay, so the deal is:

1. Logging in with a second resource *will* broadcast a second presence.
2. Logging out will *not* broadcast an "unavailable" presence unless it is the only resource that is in the room.
3. Kicking or banning a user *will* instantly and simultaneously broadcast an unavailable presence for all their resources.

Point 2 means that any effort to track multiple resources on the client side is futile. Multiple resources can be seen entering, but not leaving.

This bug can be fixed by silently ignoring any logouts from users that aren't in the room roster anymore. Oh, and point 2) could be worth reporting as an ejabberd bug. It's certainly inconvenient and inconsistent.

**Comment by cburschka** [comment]
This should fix it good.
