### ISSUE TITLE
Utilize XEP-0049 for storing certain settings?

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#261]
(whoops, submitted without a body)

XEP-0049 allows the server to hold onto arbitrary XML on behalf of the user. Could be handy to store certain settings things for users who use multiple browsers/browser sessions.

**Comment by cburschka** [comment]
Interesting... very interesting.

**Comment by cburschka** [comment]
It does seem to work on ejabberd:

```xml
   <iq xmlns="jabber:client" type="set" id="10:sendIQ">
      <query xmlns="jabber:iq:private">
         <cadence xmlns="cadence:prefs">
            <test>Hello World</test>
         </cadence>
      </query>
   </iq>
```

```xml
   <iq xmlns="jabber:client" from="Arancaytar@calref.net"
 to="Arancaytar@calref.net/cadence/v1.9.0-calref/1433325515381" id="10:sendIQ" type="result">
      <query xmlns="jabber:iq:private" />
   </iq>
```

```xml
   <iq xmlns="jabber:client" type="get" id="11:sendIQ">
      <query xmlns="jabber:iq:private">
         <cadence xmlns="cadence:prefs" />
      </query>
   </iq>
```

```xml
   <iq xmlns="jabber:client" from="Arancaytar@calref.net"
   to="Arancaytar@calref.net/cadence/v1.9.0-calref/1433325515381" id="11:sendIQ" type="result">
      <query xmlns="jabber:iq:private">
         <cadence xmlns="cadence:prefs">
            <test>Hello World</test>
         </cadence>
      </query>
   </iq>
```

All that's needed is a function to turn `config.settings` into XML, and to read an XML stanza back into a config.settings object.

**Comment by cburschka** [comment]
I mean, theoretically you could just dump the `config.settings` as one big JSON string into an XML tag, but... :aaaaa:

**Comment by cburschka** [comment]
I just realized that this will also require some thought on synchronization and conflict resolution. If I change settings on one computer, then change them on a second computer before connecting, how do the changes get applied?

A timestamp on each settings key? Or maybe offline settings changes are queued to get applied after synchronization?

**Comment by cburschka** [comment]
Thoughts: It should be possible to log into an account from a blank session and have your settings synchronized automatically without prompting.

This means that settings should either be synchronized by default (questionable) or the decision to auto-sync should be stored remotely:

1. Client connects
2. Client retrieves settings
3. Client sees "auto-sync" flag in the remote settings.
4. Client applies settings.

Likewise, if you are logging into an account after locally changing the settings, those changes should be uploaded.

However, there should be a prompt if the settings have been altered both on the server and on the client since the last sync:

* Overwrite local with remote
* Overwrite remote with local
* Do not synchronize yet

**Comment by cburschka** [comment]
> Client sees "auto-sync" flag in the remote settings.

Or maybe the fact that those settings exist in the first place should be enough. If you disabled syncing, after all, there wouldn't be a remote session.

So we have these scenarios. Your local settings have a sync username, a sync timestamp, and a mod timestamp.

1. No local sync settings, log into account without remote settings. The client has a shiny button marked "Synchronize settings". If you press it, local sync settings are set, and settings are uploaded.
2. No local sync settings, log into account with remote settings. The settings are automatically downloaded and applied.
3. Local sync settings, log into different account without remote settings. No sync. Pressing "Synchronize settings" asks you to confirm before changing your local sync account and uploading.
4. Local sync settings, log into different account with remote settings. No sync. Pressing the button gives you options (either will change your local sync account):
  1. Discard local and download
  2. Discard remote and upload
5. Local sync settings, log into the sync account, but find no remote data. No sync (it's been disabled from another browser). See (1)
6. Local sync settings, log into the sync account with remote data:
  1. All timestamps match. No change.
  2. Sync timestamp = remote timestamp. Upload.
  3. Sync timestamp = mod timestamp. Download
  4. Sync timestamp < mod timestamp and remote timestamp: Prompt as in (4).

If your account is synchronized (either automatically or because you pressed the button), the "Synchronize" button disappears and is replaced with "Delete remote settings" that does exactly what it says.

Why no option to disable syncing locally but keep remote data? Because that will simply be overwritten the next time you connect (see 2).

**Comment by cburschka** [comment]
On the assumption that the data really should be serialized to XML, and not just dumped as JSON:

https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML

**Comment by cburschka** [comment]
On second thought, I'm starting to think a more straightforward list of 

`<setting id="config.key.x.y.z" value="..." />` might be more useful than some arcane general solution.

**Comment by cburschka** [comment]
Okay, this gets the *easy* part out of the way:

```
xmpp.storeSettings(config.settings);
Promise { <state>: "pending" }
SEND <body xmlns="http://jabber.org/protocol/httpbind" rid="3587058519" sid="f7c3c7c24d44331190e9d36a75cf2df6f69ca0cf">
<iq xmlns="jabber:client" type="set" id="3:storage">
    <query xmlns="jabber:iq:private">
        <cadence xmlns="cadence:settings">
            <data name="settings" type="object">
                <data name="activeMenu" type="string">settings</data>
                <data name="activeStyle" type="string">Stygium</data>
                <data name="dateFormat" type="string">YYYY-MM-DD HH:mm:ss</data>
                <data name="contextmenu" type="string">right</data>
                <data name="markup" type="object">
                    <data name="html" type="boolean">true</data>
                    <data name="images" type="boolean">true</data>
                    <data name="links" type="boolean">true</data>
                    <data name="emoticons" type="boolean">true</data>
                    <data name="colors" type="boolean">true</data>
                </data>
                <data name="notifications" type="object">
                    <data name="blinkSpeed" type="number">2</data>
                    <data name="blinkLength" type="number">5</data>
                    <data name="sounds" type="object">
                        <data name="receive" type="string"/>
                        <data name="send" type="string">sound_2</data>
                        <data name="enter" type="string">sound_3</data>
                        <data name="leave" type="string">sound_4</data>
                        <data name="info" type="string"/>
                        <data name="error" type="string"/>
                        <data name="mention" type="string">sound_5</data>
                        <data name="privmsg" type="string"/>
                    </data>
                    <data name="soundVolume" type="string">100</data>
                    <data name="soundEnabled" type="boolean">true</data>
                    <data name="desktop" type="string">0</data>
                    <data name="leavePage" type="boolean">true</data>
                    <data name="triggers" type="array"/>
                </data>
                <data name="textColor" type="string">#00ffff</data>
                <data name="fullColor" type="boolean">false</data>
                <data name="xmpp" type="object">
                    <data name="room" type="string">lounge</data>
                    <data name="autoJoin" type="boolean">false</data>
                    <data name="sessionAuth" type="boolean">true</data>
                    <data name="resource" type="string">{client}/{version}/{timestamp}</data>
                </data>
                <data name="macros" type="object">
                    <data name="action" type="array">
                        <data type="string">/me $</data>
                    </data>
                    <data name="online" type="array">
                        <data type="string">/back $</data>
                    </data>
                    <data name="a" type="array">
                        <data type="string">/b</data>
                        <data type="string">/c</data>
                    </data>
                    <data name="d" type="array">
                        <data type="string">/e</data>
                        <data type="string">/a</data>
                    </data>
                    <data name="prefix" type="array">
                        <data type="string">/xyz $</data>
                    </data>
                    <data name="prefixprefix" type="array">
                        <data type="string">/xyz $</data>
                    </data>
                </data>
                <data name="version" type="string">1.11.0-91-g50a5afc</data>
                <data name="verbose" type="boolean">true</data>
                <data name="debug" type="number">1</data>
                <data name="locale" type="string">en</data>
            </data>
        </cadence>
    </query>
</iq>
</body>

RECV <body xmlns="http://jabber.org/protocol/httpbind">
<iq xmlns="jabber:client" from="Arancaytar@calref.net" to="Arancaytar@calref.net/cadence/1.11.0-91-g50a5afc/1464245604573" id="3:storage" type="result">
<query xmlns="jabber:iq:private"/>
</iq>
</body>

```

**Comment by cburschka** [comment]
(Also, since this stores types explicitly, I'm putting a little more code into the config-saver that turns number strings back into numbers.)

**Comment by cburschka** [comment]
Cadence can now load and store settings:

```
    xmpp.storeSettings(config.settings, config.settings.modified);
    xmpp.loadSettings().then((settings) => config.settings = settings);
```

Syncing logic will be the tricky part.

**Comment by cburschka** [comment]
Well, it took an entire rewrite of the XMPP connection handling ( #385 ), but this is starting to get practical.

**Comment by cburschka** [comment]
Possibly next: Autosync on startup.
