### ISSUE TITLE
Make the Text Input Expandable

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#420]
It's difficult to proofread submissions to the chat that are greater than two lines, so it would be cool if there was a way to expand the textbox via a click and drag control.

**Comment by sylae** [comment]
iirc just add resizable="resizable" attribute to do this. Might need some
css help to make it pretty but it'd do for a one-time thing

**Comment by cburschka** [comment]
Probably need some css magic to make sure it doesn't fuck with the layout, but yeah.

Also, I'll check this out: https://github.com/ro31337/jquery.ns-autogrow

**Comment by cburschka** [comment]
Actually the resizable property seems to be useless, because browsers put that widget into the lower-right corner.

Also, the text box is actually invisible, with the background added by the surrounding div#inputFieldContainer. So that needs to grow too.

**Comment by cburschka** [comment]
![screenshot from 2016-06-24 00-19-59](https://cloud.githubusercontent.com/assets/1448001/16322145/79512584-39a1-11e6-8156-c431286c2585.png)

**Comment by sylae** [comment]
Looks perfect to me

**Comment by Nebedia** [comment]
If the lower right becomes the resize widget, that wouldn't help too much because the textbox is already at the bottom of the screen. It would be even less useful for mobile, but I'm not sure you can put it at the top.

**Comment by sylae** [comment]
Iirc, maybe it was bleeding or maybe something else, but a site had it so
the resizable widget "grew" upwards instead of downwards. Sort of a
float:bottom I guess

**Comment by cburschka** [comment]
oh hey, actually I'm not using the native property but jQuery UI. And that has *options*! :D http://api.jqueryui.com/resizable/#option-handles

**Comment by cburschka** [comment]
Very nearly works out of the box via {handles: 'n', 'alsoResize': ui.dom.inputField} if I put the resizer on the container instead of the textarea.

![screenshot from 2016-06-24 00-29-03](https://cloud.githubusercontent.com/assets/1448001/16322409/2583d666-39a3-11e6-8529-3177c854b198.png)

The sidebars and chat pane still need to shrink accordingly, though.

Also resizing the textarea fixes its absolute position on the page, so you can't resize the window afterward.
![screenshot from 2016-06-24 00-29-03](https://cloud.githubusercontent.com/assets/1448001/16322413/2ae4601c-39a3-11e6-9021-099603c57af1.png)

**Comment by cburschka** [comment]
Yeah, it adds inline  `top` and `width` properties in pixels to both. That's bad; it would remain flush with the bottom on its own, and the width shouldn't be changeable anyway.

**Comment by cburschka** [comment]
The "alsoResize" is unnecessary since the textarea's 100% width/height settings already make it scale with the container. Removing it also fixes the width problem.

The `top` property cannot be avoided, but it *can* be removed by an event after the resizing operation is done.

    $('#inputFieldContainer').resizable({
        handles: 'n',
        stop: function () { $(this).css('top', ''); }
    });

Now we just need the chat pane and sidebar to shrink so the textarea doesn't overlap them.

**Comment by cburschka** [comment]
Moving to #160 .

**Comment by cburschka** [comment]
> @TODO: Make it a persistent setting.

Unfortunately non-trivial. The resizable widget cannot be triggered programmatically, and trying to manually set heights will run into problems (because the input field and its wrapper both get explicit heights, which are calculated by the library).

https://stackoverflow.com/questions/2523522/how-to-trigger-jquery-resizable-resize-programmatically

As the best solutions seem to be, alternately, "inject extra code into the library" or "fire the mouse events directly :aaaaa:", I'll put that on ice for now. Maybe this could be a feature.
