### ISSUE TITLE
Better ponicon sort

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#94]
I've had this idea for some time, but never had the time to implement it. As current, the ponicon menu is kind of a mess. It's sorted by character but that's about it.

As such, I'd like to recommend that the "main" ponicon menu be limited to one for each character (maybe combining some of the smaller ones into a "Misc"). Then, a click or hover event could open a submenu/collapsable/whatever to show the full set for that character.

Thoughts?

**Comment by cburschka** [comment]
(Currently scheduled for 1.6, but will definitely wait for #112.)

**Comment by cburschka** [comment]
I hate to keep putting this off, but on the plus side, I think I know a way to do this now.

* In `emoticons.conf`, the shortcuts object can be nested: Each value can be an array instead of a string; in this case, the first value is the image (like now); the second value is another object that stores sub-emoticons:

```
    ":ajhappy:": "ajhappy.png",
    ":ajbaffle:": "ajbaffle.png",
    ":ajcower:": "ajcower.png",
    ":ajfrown:": "ajfrown.png",
    ":ajlie:": "ajlie.png",
```

Becomes:

```
    ":ajhappy:": ["ajhappy.png", {
        ":ajbaffle:": "ajbaffle.png",
        ":ajcower:": "ajcower.png",
        ":ajfrown:": "ajfrown.png",
        ":ajlie:": "ajlie.png"
    },
```

* On startup, we build a "flattened" version of this object in addition to the nested one; this will be used for rendering the emoticons.

* If "compact" mode is enabled, then each nested shortcut category becomes an overlay that works similar to context menus (using the same configurable left/hover/right/none trigger as normal context menus).

* If compact mode is disabled, then the shortcuts are shown as a flattened list, just like before.

**Comment by sylae** [comment]
Another option (might be a bit easier on the presentation side? I dunno) would be to have a bpm-style filter input at the top, that filters on the text of the ponicon :code: and/or an array of tags (ie putting "rainbowdash" in the filter input would show all dashicons).

Shitty mockup follows:

![Image](https://c312441.ssl.cf1.rackcdn.com/files.calref/16/cac8f628_dragSy.png)

**Comment by cburschka** [comment]
Yeah, the filter thing is probably the way to go.

**Comment by cburschka** [comment]
Good news, I finally know a good library for this.

http://isotope.metafizzy.co/

**Comment by cburschka** [comment]
Works excellently.

Concerns:

- Need extra "tag" metadata in the YAML file because searching by name alone is unpredictable sometimes. "pink" and "pp" will both match subsets of Pinkie emotes, for example.
- Really slow when reacting to all keypresses, needs a debouncer with maybe 2-3 second timeout.

**Comment by cburschka** [comment]
Possible extra features: Sort by name, character, some kind of popularity index. Add filter buttons (top?) for each character. Isotope can do lots of things.

**Comment by cburschka** [comment]
I've recently discovered that there is no performance benefit to using a selector filter instead of a function that maps each item node onto a boolean.

And *that* means that there's no need to use extra data attributes at all. Simply get each emoticon's shortcut name, and look it up in the existing emoticon array.
